#+title: MyMedMemoir
#+subtitle: Decentralized Medical Records
#+export_file_name: index
#+setupfile: ~/.emacs.d/org-templates/projects.org

- Hackathon: https://csi-fcrit-computer.github.io/DEV-A-THON/ ([[https://web.archive.org/web/20211011153523/https://csi-fcrit-computer.github.io/DEV-A-THON/][Archive]])

| Application      | https://andinus.unfla.me/MyMedMemoir          |
| Project Homepage | https://andinus.unfla.me/projects/MyMedMemoir |
| Demo Video       | https://diode.zone/w/pm6dQGvTP77MT5KoipecPH   |

| Source          | https://git.unfla.me/MyMedMemoir       |
| GitHub (mirror) | https://github.com/andinus/MyMedMemoir |

* Team Delta Proioxis

- [[https://github.com/karishmarajput][Karishma]]
- [[https://github.com/RishiRats][Rishi]]
- [[https://github.com/Jkdxbns][Justin]]
- [[https://github.com/blanklavender][Mahima]]
- [[https://github.com/lishakothari][Lisha]]
- [[https://github.com/andinus][Andinus]]

* Thoughts

** Andinus

#+begin_quote
The idea behind the project was to create an application for users to
store their medical records. It would be stored on Tezos blockchain.

Currently, the storage is not encrypted and is shared between all the
users, the storage can be separated in the smart contract, this will
also prevent other's from editing one's records. For encryption we can
ask the user for a key on every login and the records would be encrypted
with that key.

This probably wasn't the best use of technologies, I think it's best to
use them for data that is to be public information. It would be
distributed and you always know the source of the information, knowing
the source is something we didn't do anything with in this project.

That said, it was fun to work on this!

- https://andinus.unfla.me/writings/2021/csi-hackathon.html
#+end_quote

** blanklavender

#+begin_quote
This project was a great learning experience as I took my first dive into the world of blockchain and cryptocurrency. I worked on the front-end part of the medical records. In the entire duration of the hackathon, I learnt a lot from my teammates and was able to step up my programming skills to a new level. All in all, It was exciting to build an application but under a time constraint.
#+end_quote

* Development

Memoir contract is written with ~smartpy~.

- ~landing/~: Host at root.
- ~public/~: Host at ~App/~.

* License

#+begin_src
MyMedMemoir - Decentralized Medical Records
Copyright (C) 2021, Team Delta Proioxis

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
#+end_src
